
distortion_parameters:
   k1: 0
   k2: 0
   p1: 0
   p2: 0
   k3: 0

# todo: fix these
projection_parameters:
   fx: 320
   fy: 320
   cx: 320
   cy: 240
   s: 0

# todo: fix these
image_dimensions:
  #w: 400
  #h: 300
  w: 640
  h: 480

rotation_offset:
  roll_deg: 0
  pitch_deg: 0
  yaw_deg: 0